const rig=document.querySelector('#packRig'),tearHandle=document.querySelector('#tearHandle'),mouthHandle=document.querySelector('#mouthHandle'),instruction=document.querySelector('#instruction'),sub=document.querySelector('#subinstruction'),hint=document.querySelector('#hint'),stateLabel=document.querySelector('#stateLabel'),bar=document.querySelector('.progress'),soundBtn=document.querySelector('#sound'),accessible=document.querySelector('#accessibleOpen');
const STATES=['SEALED','TEAR_GRABBED','TEARING','TEAR_PARTIAL','TEAR_COMPLETE','PACK_OPENING','PACK_COMPLETE'];let state='SEALED',tear=0,mouth=0,pointer=null,startX=0,startY=0,startTear=0,startMouth=0,lastX=0,lastTime=0,audioState='available',sound=false,audio;
function setState(next){if(!STATES.includes(next))return;state=next;rig.dataset.state=next;rig.className='pack-rig '+(next==='TEAR_COMPLETE'?'state-tear-complete':next==='PACK_OPENING'?'state-pack-opening':next==='PACK_COMPLETE'?'state-pack-open':'state-'+next.toLowerCase().replaceAll('_','-'));stateLabel.textContent=next;if(next==='TEAR_COMPLETE'){document.body.classList.add('post-tear');instruction.textContent='NOW PULL THE PACK OPEN';sub.textContent='Drag the front edge downward.'}if(next==='PACK_COMPLETE'){document.body.classList.add('pack-finished');instruction.textContent='';sub.textContent='';hint.textContent='OPENING COMPLETE · CARDS HELD FOR APPROVAL'}}
function render(){rig.style.setProperty('--tear',tear.toFixed(4));rig.style.setProperty('--mouth',mouth.toFixed(4));bar.style.setProperty('--overall',(tear<1?tear*.72:.72+mouth*.28).toFixed(4))}
function getAudio(){audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(e=>console.warn('AIR TORENZA audio resume unavailable',e));return audio}
function unlockAudio(){if(audioState!=='available')return;try{getAudio();audioState='on';sound=true;soundBtn.textContent='SOUND ON';soundBtn.setAttribute('aria-pressed','true')}catch(e){audioState='off';sound=false;soundBtn.textContent='SOUND OFF';console.warn('AIR TORENZA audio unavailable',e)}}
function noise(duration,filterType,freq,q,gain){if(!sound)return;try{const c=getAudio(),len=Math.max(1,Math.floor(c.sampleRate*duration)),buf=c.createBuffer(1,len,c.sampleRate),a=buf.getChannelData(0);for(let i=0;i<len;i++){const envelope=Math.pow(1-i/len,1.7);a[i]=(Math.random()*2-1)*envelope}const src=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();src.buffer=buf;filter.type=filterType;filter.frequency.value=freq;filter.Q.value=q;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);src.connect(filter).connect(g).connect(c.destination);src.start()}catch(e){console.warn('AIR TORENZA sound cue unavailable',e)}}
function dryClick(){noise(.026,'highpass',1900,.8,.09)}function rip(speed){if(speed<.015)return;const strength=Math.min(1,Math.max(.18,speed*1.4));noise(.065,'bandpass',1450+strength*650,.7,.035+strength*.04);noise(.04,'highpass',3600,.5,.012+strength*.014)}function crispSnap(){noise(.038,'highpass',1150,.7,.12);setTimeout(()=>noise(.022,'bandpass',3100,1.1,.065),22)}function foilRustle(speed){if(speed<.01)return;const strength=Math.min(1,.2+speed*.4);noise(.085,'bandpass',650+strength*500,.55,.025+strength*.035)}
soundBtn.addEventListener('click',()=>{if(audioState==='available'){unlockAudio();dryClick();return}sound=!sound;audioState=sound?'on':'off';soundBtn.textContent=`SOUND ${sound?'ON':'OFF'}`;soundBtn.setAttribute('aria-pressed',String(sound));if(sound)dryClick()});
tearHandle.addEventListener('pointerdown',e=>{if(!['SEALED','TEAR_PARTIAL'].includes(state))return;e.preventDefault();unlockAudio();dryClick();document.body.classList.add('interaction-started');pointer=e.pointerId;tearHandle.setPointerCapture(pointer);startX=e.clientX;startTear=tear;lastX=e.clientX;lastTime=performance.now();setState('TEAR_GRABBED');hint.textContent='';tearHandle.style.cursor='grabbing'});
tearHandle.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||!['TEAR_GRABBED','TEARING'].includes(state))return;e.preventDefault();const rect=rig.getBoundingClientRect(),next=Math.max(startTear,Math.min(1,startTear+(e.clientX-startX)/(rect.width*.68))),now=performance.now(),speed=Math.abs(e.clientX-lastX)/Math.max(1,now-lastTime);if(Math.abs(next-tear)>.002){tear=next;setState('TEARING');rip(speed);render()}lastX=e.clientX;lastTime=now});
function endTear(e){if(e.pointerId!==pointer)return;pointer=null;tearHandle.style.cursor='grab';if(tear>=.9)completeTear();else if(tear>=.85){rig.classList.add('snapping');tear=1;render();setTimeout(completeTear,230)}else{setState('TEAR_PARTIAL');hint.textContent='KEEP DRAGGING';setTimeout(()=>{rig.classList.add('resetting');tear=0;render();setTimeout(()=>{rig.classList.remove('resetting');setState('SEALED');hint.textContent=''},470)},500)}}tearHandle.addEventListener('pointerup',endTear);tearHandle.addEventListener('pointercancel',endTear);
function completeTear(){tear=1;render();rig.classList.remove('snapping','resetting','auto-opening');setState('TEAR_COMPLETE');hint.textContent='';crispSnap()}
mouthHandle.addEventListener('pointerdown',e=>{if(!['TEAR_COMPLETE','PACK_OPENING'].includes(state))return;e.preventDefault();pointer=e.pointerId;mouthHandle.setPointerCapture(pointer);startY=e.clientY;startMouth=mouth;lastTime=performance.now();setState('PACK_OPENING')});
mouthHandle.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||state!=='PACK_OPENING')return;e.preventDefault();const rect=rig.getBoundingClientRect(),next=Math.max(startMouth,Math.min(1,startMouth+(e.clientY-startY)/(rect.height*.24))),now=performance.now(),speed=Math.abs(next-mouth)/Math.max(1,now-lastTime)*1000;if(Math.abs(next-mouth)>.003){mouth=next;foilRustle(speed);render()}lastTime=now});
function endMouth(e){if(e.pointerId!==pointer)return;pointer=null;if(mouth>=.75){rig.classList.add('snapping');mouth=1;render();setTimeout(()=>{rig.classList.remove('snapping');setState('PACK_COMPLETE')},230)}else{mouth=0;rig.classList.add('resetting');render();setTimeout(()=>{rig.classList.remove('resetting');setState('TEAR_COMPLETE');hint.textContent='PULL FARTHER'},470)}}mouthHandle.addEventListener('pointerup',endMouth);mouthHandle.addEventListener('pointercancel',endMouth);
accessible.addEventListener('click',()=>{document.body.classList.add('interaction-started');unlockAudio();dryClick();if(state==='PACK_COMPLETE'){location.reload();return}pointer=null;hint.textContent='ACCESSIBLE OPENING';setState('TEARING');rig.classList.add('auto-opening');tear=1;render();setTimeout(()=>{completeTear();setState('PACK_OPENING');rig.classList.add('auto-mouth');mouth=1;foilRustle(.6);render();setTimeout(()=>{rig.classList.remove('auto-mouth');setState('PACK_COMPLETE')},850)},1450)});render();
