let soundMaster,soundOutput,pullNoiseSource,pullNoiseGain,pullSilenceTimer;
function getSoundMaster(){if(soundMaster)return soundMaster;const c=getAudio(),limiter=c.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=8;limiter.ratio.value=12;limiter.attack.value=.003;limiter.release.value=.1;soundOutput=c.createGain();soundOutput.gain.value=.92;limiter.connect(soundOutput).connect(c.destination);soundMaster=limiter;return soundMaster}
function noise(duration,filterType,freq,q,gain){if(!sound)return;try{const c=getAudio(),len=Math.max(1,Math.floor(c.sampleRate*duration)),buf=c.createBuffer(1,len,c.sampleRate),a=buf.getChannelData(0);for(let i=0;i<len;i++){const envelope=Math.pow(1-i/len,1.55);a[i]=(Math.random()*2-1)*envelope}const src=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();src.buffer=buf;filter.type=filterType;filter.frequency.value=freq;filter.Q.value=q;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);src.connect(filter).connect(g).connect(getSoundMaster());src.start()}catch(e){console.warn('AIR TORENZA sound cue unavailable',e)}}
function dryClick(){noise(.032,'highpass',1750,.85,.13)}
function rip(speed){if(speed<.015)return;const strength=Math.min(1,Math.max(.2,speed*1.45));noise(.072,'bandpass',1350+strength*700,.7,.075+strength*.085);noise(.047,'highpass',3300,.55,.022+strength*.035)}
function crispSnap(){noise(.042,'highpass',1050,.75,.145);setTimeout(()=>noise(.026,'bandpass',2950,1.05,.085),18)}
function startPullNoise(){if(!sound||pullNoiseSource)return;const c=getAudio(),len=c.sampleRate,buf=c.createBuffer(1,len,c.sampleRate),a=buf.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*(.55+.45*Math.sin(i*.013));pullNoiseSource=c.createBufferSource();pullNoiseSource.buffer=buf;pullNoiseSource.loop=true;const filter=c.createBiquadFilter();filter.type='bandpass';filter.frequency.value=850;filter.Q.value=.55;pullNoiseGain=c.createGain();pullNoiseGain.gain.value=.0001;pullNoiseSource.connect(filter).connect(pullNoiseGain).connect(getSoundMaster());pullNoiseSource.start()}
function foilRustle(speed){if(!sound||speed<.01)return;try{startPullNoise();const c=getAudio(),level=Math.min(.13,.055+Math.min(1,speed*.35)*.075);pullNoiseGain.gain.cancelScheduledValues(c.currentTime);pullNoiseGain.gain.setTargetAtTime(level,c.currentTime,.012);clearTimeout(pullSilenceTimer);pullSilenceTimer=setTimeout(()=>{if(pullNoiseGain)pullNoiseGain.gain.setTargetAtTime(.0001,getAudio().currentTime,.018)},70)}catch(e){console.warn('AIR TORENZA foil rustle unavailable',e)}}
function stopPullNoise(){clearTimeout(pullSilenceTimer);if(pullNoiseGain)pullNoiseGain.gain.setTargetAtTime(.0001,getAudio().currentTime,.012);if(pullNoiseSource){const old=pullNoiseSource;setTimeout(()=>{try{old.stop()}catch{}},90)}pullNoiseSource=null;pullNoiseGain=null}
function openingPop(){noise(.05,'lowpass',950,.65,.12);setTimeout(()=>noise(.024,'highpass',2100,.7,.045),14)}
mouthHandle.addEventListener('pointerup',()=>{const completed=mouth>=.75;stopPullNoise();if(completed)setTimeout(openingPop,220)});mouthHandle.addEventListener('pointercancel',stopPullNoise);
