const cardStage=document.querySelector('#cardStage'),stackAction=document.querySelector('#cardStackAction'),demoCards=[...document.querySelectorAll('.demo-card')],openAgain=document.querySelector('#openAgain');
const CARD_STATES=['PACK_OPENING_COMPLETE','CARDS_WAITING','CARDS_RISING','CARDS_RISEN','CARDS_FANNING','CARDS_READY'];let cardState='';
function setCardState(next){if(!CARD_STATES.includes(next))return;cardState=next;rig.dataset.state=next;document.body.classList.remove('pack-finished',...CARD_STATES.map(s=>s.toLowerCase().replaceAll('_','-')));document.body.classList.add('cards-active',next.toLowerCase().replaceAll('_','-'))}
function cardNoise(duration,type,freq,q,gain){noise(duration,type,freq,q,gain)}
function cardSlide(reduced){if(!sound)return;const count=reduced?2:7,step=reduced?80:135;for(let i=0;i<count;i++)setTimeout(()=>cardNoise(.1,'bandpass',1250+i*85,.55,.028),i*step)}
function cardTap(){cardNoise(.027,'highpass',1850,.7,.065)}
function cardFlick(i){cardNoise(.034,'bandpass',2100+i*95,.65,.038)}
function beginCards(){setCardState('PACK_OPENING_COMPLETE');instruction.textContent='';sub.textContent='';hint.textContent='';const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;setTimeout(()=>{setCardState('CARDS_WAITING');requestAnimationFrame(()=>{setCardState('CARDS_RISING');cardSlide(reduced);setTimeout(()=>{setCardState('CARDS_RISEN');cardTap();instruction.textContent='YOUR CARDS HAVE ARRIVED';sub.textContent='Tap the stack to place them on the table.';stackAction.focus()},reduced?240:1080)})},reduced?80:320)}
function fanCards(){if(cardState!=='CARDS_RISEN')return;setCardState('CARDS_FANNING');stackAction.disabled=true;instruction.textContent='PLACING YOUR CARDS';sub.textContent='';const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;demoCards.forEach((card,i)=>setTimeout(()=>cardFlick(i),reduced?i*40:i*105));setTimeout(()=>{setCardState('CARDS_READY');instruction.textContent='TAP ONE CARD AT A TIME';sub.textContent='Five face-down AIR TORENZA cards are ready.';demoCards.forEach(card=>card.disabled=false);demoCards[0].focus()},reduced?260:1120)}
stackAction.addEventListener('click',fanCards);stackAction.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fanCards()}});openAgain.addEventListener('click',()=>location.reload());
new MutationObserver(()=>{if(rig.dataset.state==='PACK_COMPLETE'&&!cardState)beginCards()}).observe(rig,{attributes:true,attributeFilter:['data-state']});
