/* Card 001-only reveal state machine. */
const revealStates=['CARD_001_READY','CARD_001_FLIPPING','CARD_001_REVEALED'],card001=demoCards[0];let revealState='';
demoCards.forEach((card,i)=>{card.dataset.card=String(i+1).padStart(3,'0');if(i===0)card.setAttribute('aria-label','Reveal Card 001 — London 1966');else card.setAttribute('aria-label',`Face-down Card ${String(i+1).padStart(3,'0')} — reveal unavailable`)});
const discovery=document.createElement('p');discovery.className='card-001-label';discovery.setAttribute('aria-live','polite');discovery.innerHTML='CARD 001 DISCOVERED<span>London 1966 — Classic Route</span>';openAgain.before(discovery);
function setRevealState(next){if(!revealStates.includes(next))return;revealState=next;rig.dataset.state=next;document.body.classList.remove(...revealStates.map(s=>s.toLowerCase().replaceAll('_','-')));document.body.classList.add(next.toLowerCase().replaceAll('_','-'))}
function flipFlick(){noise(.035,'highpass',2250,.65,.082)}function flipLand(){noise(.024,'highpass',1800,.7,.052)}
function prepareCard001(){if(revealState)return;setRevealState('CARD_001_READY');demoCards.forEach((card,i)=>card.disabled=i!==0);card001.focus()}
function revealCard001(){if(revealState!=='CARD_001_READY')return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,duration=reduced?260:720;setRevealState('CARD_001_FLIPPING');demoCards.forEach(card=>card.disabled=true);requestAnimationFrame(()=>card001.classList.add('is-flipping'));setTimeout(flipFlick,duration/2);setTimeout(()=>{card001.classList.remove('is-flipping');card001.classList.add('is-revealed');setRevealState('CARD_001_REVEALED');flipLand();instruction.textContent='CARD 001 DISCOVERED';sub.textContent='London 1966 — Classic Route';card001.setAttribute('aria-label','Card 001 discovered: London 1966, Classic Route');card001.disabled=false;card001.focus()},duration)}
card001.addEventListener('click',revealCard001);new MutationObserver(()=>{if(rig.dataset.state==='CARDS_READY')prepareCard001()}).observe(rig,{attributes:true,attributeFilter:['data-state']});
