const rig=document.querySelector('#packRig'),tearHandle=document.querySelector('#tearHandle'),mouthHandle=document.querySelector('#mouthHandle'),instruction=document.querySelector('#instruction'),sub=document.querySelector('#subinstruction'),hint=document.querySelector('#hint'),stateLabel=document.querySelector('#stateLabel'),bar=document.querySelector('.progress'),soundBtn=document.querySelector('#sound'),accessible=document.querySelector('#accessibleOpen');
const STATES=['SEALED','TEAR_GRABBED','TEARING','TEAR_PARTIAL','TEAR_COMPLETE','PACK_OPENING','PACK_COMPLETE'];let state='SEALED',tear=0,mouth=0,pointer=null,startX=0,startY=0,startTear=0,startMouth=0,lastX=0,lastTime=0,sound=false,audio;
function setState(next){if(!STATES.includes(next))return;state=next;rig.dataset.state=next;rig.className='pack-rig '+(next==='TEAR_COMPLETE'?'state-tear-complete':next==='PACK_OPENING'?'state-pack-opening':next==='PACK_COMPLETE'?'state-pack-open':'state-'+next.toLowerCase().replaceAll('_','-'));stateLabel.textContent=next;if(next==='TEAR_COMPLETE'){instruction.textContent='PULL OPEN';sub.textContent='Drag the front upper foil flap downward.'}if(next==='PACK_COMPLETE'){instruction.textContent='PACK MOUTH OPEN';sub.textContent='Physical opening approved state. Cards remain held.';stateLabel.classList.add('pack-open-note')}}
function render(){rig.style.setProperty('--tear',tear.toFixed(4));rig.style.setProperty('--mouth',mouth.toFixed(4));bar.style.setProperty('--overall',(tear<1?tear*.72:.72+mouth*.28).toFixed(4))}
function ctx(){audio??=new(window.AudioContext||window.webkitAudioContext)();return audio}function clickTone(freq=260,d=.045,gain=.035){if(!sound)return;try{const c=ctx(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){console.warn('AIR TORENZA sound cue unavailable',e)}}
function tearNoise(speed){if(!sound||speed<.015)return;try{const c=ctx(),len=Math.floor(c.sampleRate*.045),buf=c.createBuffer(1,len,c.sampleRate),a=buf.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*(1-i/len);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=buf;f.type='bandpass';f.frequency.value=1300+Math.min(speed,2)*800;g.gain.value=Math.min(.055,.012+speed*.025);s.connect(f).connect(g).connect(c.destination);s.start()}catch(e){console.warn('AIR TORENZA tear sound unavailable',e)}}
soundBtn.addEventListener('click',()=>{sound=!sound;soundBtn.textContent=`SOUND ${sound?'ON':'OFF'}`;soundBtn.setAttribute('aria-pressed',String(sound));if(sound)clickTone(420,.07,.025)});
tearHandle.addEventListener('pointerdown',e=>{if(!['SEALED','TEAR_PARTIAL'].includes(state))return;e.preventDefault();pointer=e.pointerId;tearHandle.setPointerCapture(pointer);startX=e.clientX;startTear=tear;lastX=e.clientX;lastTime=performance.now();setState('TEAR_GRABBED');hint.textContent='';clickTone();tearHandle.style.cursor='grabbing'});
tearHandle.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||!['TEAR_GRABBED','TEARING'].includes(state))return;e.preventDefault();const rect=rig.getBoundingClientRect(),next=Math.max(startTear,Math.min(1,startTear+(e.clientX-startX)/(rect.width*.68))),now=performance.now(),speed=Math.abs(e.clientX-lastX)/Math.max(1,now-lastTime);if(Math.abs(next-tear)>.002){tear=next;setState('TEARING');tearNoise(speed);render()}lastX=e.clientX;lastTime=now});
function endTear(e){if(e.pointerId!==pointer)return;pointer=null;tearHandle.style.cursor='grab';if(tear>=.9)completeTear();else if(tear>=.85){rig.classList.add('snapping');tear=1;render();setTimeout(completeTear,230)}else{setState('TEAR_PARTIAL');hint.textContent='KEEP DRAGGING';setTimeout(()=>{rig.classList.add('resetting');tear=0;render();setTimeout(()=>{rig.classList.remove('resetting');setState('SEALED');hint.textContent=''},470)},500)}}tearHandle.addEventListener('pointerup',endTear);tearHandle.addEventListener('pointercancel',endTear);
function completeTear(){tear=1;render();rig.classList.remove('snapping','resetting','auto-opening');setState('TEAR_COMPLETE');hint.textContent='TOP STRIP REMOVED';clickTone(340,.045,.03);setTimeout(()=>clickTone(560,.16,.025),65)}
mouthHandle.addEventListener('pointerdown',e=>{if(!['TEAR_COMPLETE','PACK_OPENING'].includes(state))return;e.preventDefault();pointer=e.pointerId;mouthHandle.setPointerCapture(pointer);startY=e.clientY;startMouth=mouth;lastTime=performance.now();setState('PACK_OPENING');hint.textContent='';clickTone(190,.04,.018)});
mouthHandle.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||state!=='PACK_OPENING')return;e.preventDefault();const rect=rig.getBoundingClientRect(),next=Math.max(startMouth,Math.min(1,startMouth+(e.clientY-startY)/(rect.height*.24))),now=performance.now(),speed=Math.abs(next-mouth)/Math.max(1,now-lastTime)*1000;if(Math.abs(next-mouth)>.003){mouth=next;tearNoise(speed*.25);render()}lastTime=now});
function endMouth(e){if(e.pointerId!==pointer)return;pointer=null;if(mouth>=.75){rig.classList.add('snapping');mouth=1;render();setTimeout(()=>{rig.classList.remove('snapping');setState('PACK_COMPLETE');hint.textContent='READY FOR CARDS-EMERGE APPROVAL';clickTone(150,.22,.022)},230)}else{mouth=0;rig.classList.add('resetting');render();setTimeout(()=>{rig.classList.remove('resetting');setState('TEAR_COMPLETE');hint.textContent='PULL FARTHER'},470)}}mouthHandle.addEventListener('pointerup',endMouth);mouthHandle.addEventListener('pointercancel',endMouth);
accessible.addEventListener('click',()=>{if(state==='PACK_COMPLETE'){location.reload();return}pointer=null;hint.textContent='ACCESSIBLE OPENING';rig.classList.add('auto-opening');tear=1;render();setState('TEARING');setTimeout(()=>{completeTear();rig.classList.add('auto-mouth');setState('PACK_OPENING');mouth=1;render();setTimeout(()=>{rig.classList.remove('auto-mouth');setState('PACK_COMPLETE');hint.textContent='READY FOR CARDS-EMERGE APPROVAL'},850)},1450)});render();
